name: AutoRepair
main: com.lostaris.bukkit.ItemRepair.AutoRepairPlugin
version: 1.73
commands:
  repair:
    description: uses one or more items to repair a tool or armour
    aliases: rep
    usage: |
      Incorrect usage of command /<command>.
      Proper usage of /<command>
       '/<command> [itemslot 1-9]' repair item.
       '/<command> [itemslot 1-9] ?' Check required repair materials.
       '/<command> [itemslot 1-9] dmg' Check number of uses left.
       '/<command> <?,dmg> as above but for current item.
       '/<command> arm' repairs all your equipped armour.
       '/<command> arm ?' Check armour repair materials.
       '/<command> reload' Reloads the config files.